# Use the official MeiliSearch image as the base
FROM getmeili/meilisearch:v1.12

# Set environment variables for MeiliSearch
# (you can override these variables at runtime if needed)
ENV MEILI_MASTER_KEY=a0Mfp5S-WKAQ5_dtAARW3EopM6eij7u-OrrWo4JqTIk
ENV MEILI_IMPORT_DUMP=/data/data.dump

COPY ./data /data